### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by KrisYiu** [OpenNos/OpenNos#577] opened 2016-05-12 13:11 UTC
Hi all.. i'm Kris from HongKong.
i meet a problem when i change the words to Chinese in Mysql DB. eg. Char ID (Rename by mysql command), shop name, item name, monster name.

img: [http://postimg.org/image/l50cg0bsx/](http://postimg.org/image/l50cg0bsx/)

and i test the words not form mysql.
added the words at the last of the $Help. (Error sill here)
chat system in game. (Shown correctly)
img: [http://postimg.org/image/ihcqb5eip/](http://postimg.org/image/ihcqb5eip/)

May i know how to solve please?
:) thx a lot

**Comment by chucktheripper** [comment] 2016-05-12 13:34
This could be an encoding problem as we send and receive ascii i guess, utf8 will fix it

**Comment by KrisYiu** [comment] 2016-05-12 16:21
Thanks :)..
I should work in WorldEncryption or where..?

**Comment by chucktheripper** [comment] 2016-05-12 16:22
No more in send & receive packet, encryption / decryption works

**Comment by 0Lucifer0** [comment] 2016-05-12 16:43
The problem is that We need to send and receive byte but utf-8 use 2 byte so We need to change decryption encryption and send/receive

**Comment by chucktheripper** [comment] 2016-05-13 15:03
Do we really need to change the Encryption/Decryption?

**Comment by 0Lucifer0** [comment] 2016-05-13 15:15
Just modify a little bit i think

**Comment by KrisYiu** [comment] 2016-05-13 17:55
big5 is ACSII? 
i do it already w/ big5 codepage.

**Comment by KrisYiu** [comment] 2016-05-13 17:57
img: [http://postimg.org/image/jvfvb5cg1/](http://postimg.org/image/jvfvb5cg1/)

**Comment by chucktheripper** [comment] 2016-05-13 18:03
So did you fix it?

**Comment by KrisYiu** [comment] 2016-05-13 18:08
yup. but i duuno how to set it be multi-lang.

may i know ur id in elitepvpers.

**Comment by chucktheripper** [comment] 2016-05-13 18:09
its the same as here

**Comment by KrisYiu** [comment] 2016-05-13 18:11
plx check PM.
i sent it to chucktheripper & 0Lucifer0

**Comment by MasterDomino** [comment] 2016-10-03 15:19
seems like it came back

**Comment by earthnash** [comment] 2016-10-03 15:52
i send packet from client-->  say ทดสอบ
but server receive my packet-->  say ?????
if i had server send packet--> say ทดสอบ
client receive--> say ทดสอบ
my language is Thai 
sorry i don't know how to explain
again sorry for my bad English :(

**Comment by 0Lucifer0** [comment] 2016-10-06 14:28
so encryption works and decryption don't ?

**Comment by 0Lucifer0** [comment] 2016-10-06 14:41
should be fixed reopen if not

**Comment by 0Lucifer0** [comment] 2016-10-09 17:39
Already in other issue

**Closed by 0Lucifer0** 2016-10-09 17:39 UTC
Labels: bug
