### ISSUE TITLE
Save character failed

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1283] opened 2016-10-18 17:50 UTC
![image](https://cloud.githubusercontent.com/assets/15254478/19489551/f6e99e74-956b-11e6-8035-6359be2ba5a1.png)

**Comment by chucktheripper** [comment] 2016-10-20 06:15
Caused by wrong instantiation of ItemInstance, should be fixed.

**Closed** 2016-10-20 06:15 UTC
Labels: bug
