### ISSUE TITLE
Drops by player only show after you reenter the map

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1621] opened 2016-11-28 00:48 UTC
Reproduce:
- two players on a map next to each other
- one players drops an item (for example Seed)
- noone of the players can see the dropped item
- re-enter the map (for example with $Teleport to do it quickly)

Result: Player who re-entered the map can see and pick up the item.

**Comment by Ciapa** [comment] 2016-11-28 04:30
Seems to be caused by my Drop Protection.
Will be fixed later

**Closed** 2016-11-28 16:17 UTC
Labels: bug
