### ISSUE TITLE
Server Actualisation Problem

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1153] opened 2016-10-03 18:45 UTC
If you bet something by the normal way (eg : Rarity bet) and it's worked fine, the server don't refresh the item Name & Color linked to the rarity level. 

I have a R0 weapon, then my bet take it R2, in my inventory the item stay R0 color, but change by right clicking on it. The item change while refreshing the server by disconnect then reconnect.

**Comment by MasterDomino** [comment] 2016-10-03 18:53
someone broke the generateinventoryadd

**Comment by chucktheripper** [comment] 2016-10-03 19:17
Packet order problem maybe!

**Comment by Digitalis87** [comment] 2016-10-03 19:38
I'm the uploader of this issue on MyTale Forum. 
After Few test with Uppermost 

- Item change in the real Rarity level if equipped.
- Rarity is good in trade for the "buyer" (The person who ill recieve the item)

:)

**Comment by itemhack** [comment] 2016-10-03 19:56
maybe we need to refreh the inventory

**Comment by MasterDomino** [comment] 2016-10-04 08:51
no we dont someone changed something with GenerateInventoryAdd which is important

**Comment by Digitalis87** [comment] 2016-10-04 09:26
The problem still happend. Tried 1 min ago.

**Comment by MasterDomino** [comment] 2016-10-04 09:38
which problem because now it shouldnt and after what does it happen?

**Comment by Digitalis87** [comment] 2016-10-04 09:57
The problem is that the equipment in the inventory is not updated.
After managing a rarity bet @Teodor Topp, scrolling my mouse over the object does not show the new rarity.

**Comment by chucktheripper** [comment] 2016-10-04 11:54
Please check packet receive order.

**Comment by 0Lucifer0** [comment] 2016-10-04 11:57
did you use last update?

**Comment by Digitalis87** [comment] 2016-10-04 12:06
Did it help ?
https://gyazo.com/9dce9766f72ce3892e7bbdbf9ad33fe8

**Comment by MasterDomino** [comment] 2016-10-04 14:02
havent you use $Rarify command? because for me it looks suspicious i properly placed GenerateInventoryAdd now soo it shouldnt occur

**Comment by chucktheripper** [comment] 2016-10-04 14:05
Ah, no Broadcast problem, it has nothing to do with broadcast xD

**Comment by Digitalis87** [comment] 2016-10-04 14:16
No i tried by normal way (@TeodorTopp NPC) with 500g + Cella Powder.

**Comment by 0Lucifer0** [comment] 2016-10-04 14:18
Are You sure to use last update ?

**Comment by Digitalis87** [comment] 2016-10-04 14:20
I've tried on test server yes. Want me to try once again ?

**Comment by Digitalis87** [comment] 2016-10-04 14:25
Not working yet. Tried. My # **non** developer sense tell me it should be a problem close to the SP perf visual refresh bug. But i'm not sure.

**Comment by Uppermost** [comment] 2016-10-04 15:09
I close it for the moment, the problem seem's to be fix.

**Comment by 0Lucifer0** [comment] 2016-10-04 15:11
The reason is the same for sp but not at the same place ;)

**Comment by Uppermost** [comment] 2016-10-04 15:15
Always not good ^^

**Comment by MasterDomino** [comment] 2016-10-04 17:34
I fixed the issue of sp already, just like this one idk what can be causing this right now i checked and placed it properly

**Closed** 2016-11-13 11:07 UTC
Labels: bug
