### ISSUE TITLE
Console Error World

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1258] opened 2016-10-16 04:58 UTC
![image](https://cloud.githubusercontent.com/assets/22244296/19415341/fc766930-936d-11e6-9523-f4c18fda399e.png)

**Comment by MyTaleON** [comment] 2016-10-16 05:50
![image](https://cloud.githubusercontent.com/assets/22244296/19415606/38a015a8-9375-11e6-9536-e6a2a9be7eca.png)

**Comment by MasterDomino** [comment] 2016-10-16 06:49
http://ben.balter.com/2014/11/06/rules-of-communicating-at-github/
read point 3 please and correct your issue

**Comment by MasterDomino** [comment] 2016-10-16 11:20
1st is #958 overflow and 2nd is fixed on latest iteminstance branch(propably) its caused by #934

**Closed by MasterDomino** 2016-10-16 11:20 UTC
