### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1473] opened 2016-11-15 22:51 UTC
https://gyazo.com/834372fbde8b40c29327cefc94bbe7f4

Farmed 1, got 2

**Comment by Uppermost** [comment] 2016-11-15 22:52
This link doesn't work please provide more information or an other link

**Comment by SasukeTale** [comment] 2016-11-15 22:59
https://gyazo.com/834372fbde8b40c29327cefc94bbe7f4

**Comment by Uppermost** [comment] 2016-11-15 23:06
Impossible for me to reproduce it at the latest version

**Comment by AzogDE** [comment] 2016-11-16 07:14
Maybe cause of traffic the server didnt checked the value or kinda this problem.

**Comment by chucktheripper** [comment] 2016-11-16 07:16
We will add a lock on get, so noone can access the inventory when currently getting the item.

**Comment by AzogDE** [comment] 2016-11-16 08:13
But this wouldnt fix the dupe with x255

**Comment by chucktheripper** [comment] 2016-11-16 08:15
The dupe bug should be fixed in the current version

**Comment by chucktheripper** [comment] 2016-11-16 08:15
(255x dupe i mean)

**Comment by AzogDE** [comment] 2016-11-16 08:15
Alright. :) Mind tell me the issue for producing that?

**Closed** 2016-11-16 15:09 UTC
Labels: not-reproducible
