### ISSUE TITLE
Delete the tempory portal $PortalTo command

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1044] opened 2016-09-23 13:06 UTC
All is on the tittle, we need to remove the Portal if we want.

**Comment by 0Lucifer0** [comment] 2016-09-23 13:07
How do you plan to do that ><

**Comment by Uppermost** [comment] 2016-09-23 13:09
I have no idea, we can maybe just add a tempory portal like 30 mins... I don't know how they do on official when there is an event

**Comment by MyTaleON** [comment] 2016-09-23 13:24
you can give the Portals an ID and than you can delete -> $RemovePortal <ID> and on the offizial it's so: GM delete the portal with the command and when you refresh the map it's  gone.

**Comment by 0Lucifer0** [comment] 2016-09-23 13:26
Or we can delete portal nearest ;)

**Comment by SC909** [comment] 2016-09-23 15:21
As MyTaleON said, you should add to $PortalTo an unique id so you could delete it like $PortalRemove ID, and you should also add, $PortalToList so it shows which portals were added by $PortalTo command.

**Comment by Uppermost** [comment] 2016-09-25 00:11
Maybe more easy Lucifer idea ;)

**Comment by 0Lucifer0** [comment] 2016-09-25 01:22
portal already have an unique id but how do you wan't to get the id >< that's the same problem

**Comment by 0Lucifer0** [comment] 2016-09-25 10:00
perhaps a general clean portal is better

**Comment by SC909** [comment] 2016-09-25 22:39
unique id can be like reference id, and it is used on official (even in time spaces, act 4 raids, sp7 raid, normal raids etc.)
a new table would be great for it.
Also a manipulation of those portals would be great (change portal type, close it, open it, delete it)

**Comment by 0Lucifer0** [comment] 2016-09-25 23:11
The problem is that if we use a unique id you won't be able to know witch id = witch portal  all USE already an unique id because of codd normal form the problem is not how to do it its how let you know the id ><

**Comment by Martazza** [comment] 2016-09-26 20:08
https://github.com/OpenNos/OpenNos/commit/d89c7a493278dc6172521164ab78bf78f68cf650

**Closed** 2016-09-27 19:15 UTC
Labels: enhancement
