### ISSUE TITLE
World Error if you try to trade with some one

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#868] opened 2016-08-30 21:38 UTC
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/18108055/dfac6a02-6f0a-11e6-80df-3a8706bbe166.PNG)

**Comment by MasterDomino** [comment] 2016-08-31 06:56
when does this occur? please more descryption.

**Comment by The-Art-Of-War** [comment] 2016-08-31 09:17
if you click on trade :)

**Comment by MasterDomino** [comment] 2016-08-31 09:18
did it showed only once? because i cant reproduce it

**Comment by The-Art-Of-War** [comment] 2016-08-31 09:29
the error is shown every single time if you click on Trade

**Comment by MasterDomino** [comment] 2016-08-31 09:51
i wasnt able to reproduce it try synchronizing repo.

**Comment by The-Art-Of-War** [comment] 2016-08-31 10:04
I will test it again and tell more about it

**Comment by DarkCacos** [comment] 2016-08-31 11:04
To me it never happened, and these days I tested the emulator very often.
Have you reparsed after recompiling the project?
After laters commits you need to reparse for many things, not just recompile.

**Comment by Uppermost** [comment] 2016-08-31 22:51
I close it because I have test some time and I have not this problem. Reopen if this error reappear

**Closed by Uppermost** 2016-08-31 22:51 UTC
Labels: not-reproducible
