### ISSUE TITLE
Damage Calculation

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1247] opened 2016-10-14 23:07 UTC
https://gyazo.com/58896232e74d3c2105d906067939a2fe

**Comment by Ciapa1** [comment] 2016-10-15 00:18
Duplicate of 1246

Am 15.10.2016 1:07 vorm. schrieb "SasukeTale" <notifications@github.com>:

**Closed** 2016-10-15 00:19 UTC
