### ISSUE TITLE
cannot use "space" select nearest moster

### ISSUE THREAD

**Issue by KrisYiu** [OpenNos/OpenNos#584] opened 2016-05-13 22:07 UTC
i'm not sure is that can use before

**Comment by chucktheripper** [comment] 2016-05-13 22:14
this is caused by skill buying / selling, there is a bug in that logic

**Comment by KrisYiu** [comment] 2016-05-13 22:16
oh~shit.. sori~ i get it... client side problem.. can close.
sorry for my silly quesion

**Comment by chucktheripper** [comment] 2016-05-14 09:35
this should actually be fixed now

**Closed by chucktheripper** 2016-05-14 09:35 UTC
Labels: bug
