### ISSUE TITLE
Private shop you can use a bug to be not sitdown

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1582] opened 2016-11-25 03:01 UTC
Use ctrl+z when you open a shop private and you use this bug to be not sitdown

**Comment by Ciapa** [comment] 2016-11-25 08:04
On official you can do the same.

**Comment by MasterDomino** [comment] 2016-11-25 08:08
Yes but we want to try to fix issue that exist on official

**Comment by friends111** [comment] 2016-11-25 14:49
maybe just disable rest while shopping?

**Comment by Ciapa** [comment] 2016-11-25 20:28
Duplicate of #1059

**Closed by Ciapa** 2016-11-25 20:28 UTC
