### ISSUE TITLE
Missing skills SP

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1532] opened 2016-11-20 01:11 UTC
And Dark Gunner misses one skill:
https://cdn.discordapp.com/attachments/245272184564482048/249701176956813312/unknown.png

**Comment by friends111** [comment] 2016-11-21 13:42
![image](https://cloud.githubusercontent.com/assets/10873097/20484692/b51d2f86-aff8-11e6-965e-0f545c25cf65.png)
Same here.

**Comment by Uppermost** [comment] 2016-11-21 13:43
W-T-F ?

**Comment by 0Lucifer0** [comment] 2016-11-21 13:46
Yes there was an issue about it for me (parser lvl skrill trouble)

**Comment by 0Lucifer0** [comment] 2016-11-21 13:47
#739

**Comment by Ciapa** [comment] 2016-11-23 22:55
This is not the same issue as #739 
Need to see what the issue is for these Specialists and their skills.

**Comment by 0Lucifer0** [comment] 2016-11-23 23:19
fixed by my last commit(unvolontary)

**Closed by 0Lucifer0** 2016-11-23 23:19 UTC
Labels: bug
